server:
  port: 9001

spring:
  application:
    name: "user-service"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"